# Site settings
course_name: Database
course_description: "This course covers the fundamentals of database management, including conceptual and logical design, as well as access and manipulation of databases, and introduces students to best practices in modeling, design, and implementation using contemporary database management systems in organizations. Students will learn how to develop database applications, beginning with the design of an Entity-Relationship (ER) model, then mapping it to a relational model, and finally transforming this second model into an application. Throughout this course, students will not only acquire theoretical knowledge but also essential practical skills for working with database systems. In the practical section of the course, PostgreSQL will be utilized as a powerful and open-source database management system."
course_semester: "1404_1"

baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://dbcs4041.miladai.ir/" # the base hostname & protocol for your site

schoolname: "Shahid Beheshti University"
schoolurl: "https://mathsci.sbu.ac.ir/"


address: |
    Shahid Beheshti University
    Tehran
    IRAN

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
